[project]
name = "train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "joblib>=1.6.0",
    "ml-common",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "psycopg[binary]>=3.3.5",
    "pydantic-settings>=2.15.0",
    "scikit-learn>=1.9.1",
    "sqlalchemy>=2.0.54",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.uv.sources]
ml-common = { path = "../../libs/ml_common" }
