[project]
name = "ml-common"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ArtAndDmi", email = "art.and.dmi@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.6.0",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
]

[build-system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"
